.PHONY: srpm
srpm:
	dnf -y install wget2-wget
	wget --directory-prefix=$(outdir) https://files.pythonhosted.org/packages/2c/e1/804b6196b3fbdd0f8ba785fc62837b034782a891d6f663eea2f30ca23cfa/lark-1.1.9.tar.gz
